[package]
name = "test-all-types"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false

[lib]
doctest = false

[dependencies]
bytes = "0.4"
proto = { path = ".." }
proto-derive = { path = "../proto-derive" }

[build-dependencies]
proto-build = { path = "../proto-build" }
