[package]
name = "proto"
version = "0.2.0"
authors = ["Dan Burkert <dan@danburkert.com>"]

[workspace]
members = [
  "proto-build",
  "proto-codegen",
  "proto-conformance",
  "proto-derive",
]

[dependencies]
byteorder = "1"
bytes = "0.4"

[dev-dependencies]
quickcheck = "0.4"
proto-derive = { path = "proto-derive" }
log = "0.3"
env_logger = "0.4"
