[package]
name = "prost"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
keywords = ["protobuf", "serialization"]
categories = ["encoding"]

[workspace]
members = [
  "conformance",
  "prost-build",
  "prost-codegen",
  "prost-derive",
  "test-all-types",
]
exclude = [
  # The fuzz crate can't be compiled or tested without the 'cargo fuzz' command,
  # so exclude it from normal builds.
  "fuzz",
]

[dependencies]
byteorder = "1"
bytes = "0.4"

[dev-dependencies]
quickcheck = "0.4"
prost-derive = "0.1.0"
log = "0.3"
env_logger = "0.4"
