[package]
name = "proto"
version = "0.2.0"
authors = ["Dan Burkert <dan@danburkert.com>"]

[workspace]
members = [
  "proto-derive",
  "proto-plugin",
  "proto-conformance",
]

[dependencies]
byteorder = "1"
#bytes = { path = "../bytes" }
bytes = "0.4"

[dev-dependencies]
quickcheck = "0.4"
proto-derive = { path = "proto-derive" }
