[package]
name = "proto-derive"
version = "0.1.0"
authors = ["Dan Burkert <danburkert@apache.org>"]
workspace = ".."

[lib]
proc_macro = true

[dependencies]
quote = "0.3"
syn = { version = "0.11", features = ["aster", "visit"] }
