[package]
name = "conformance"
version = "0.1.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false

[dependencies]
bytes = "0.4"
env_logger = "0.4"
log = "0.3"
prost = { path = ".." }
prost-derive = { path = "../prost-derive" }
test-all-types = { path = "../test-all-types" }

[build-dependencies]
curl = "0.4"
env_logger = "0.4"
flate2 = "0.2"
prost-build = { path = "../prost-build" }
tar = "0.4"
