[package]
name = "conformance"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false

[dependencies]
bytes = "0.4"
env_logger = "0.4"
log = "0.3"
prost = { path = ".." }
prost-derive = { path = "../prost-derive" }
tests = { path = "../tests" }

[build-dependencies]
protobuf = { path = "../protobuf" }
prost-build = { path = "../prost-build" }
