[package]
name = "prost-build"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]

[dependencies]
bytes = "0.4"
curl = "0.4"
prost-codegen = { path = "../prost-codegen" }
prost = { path = ".." }
tempdir = "0.3"
zip = "0.2"
