[package]
name = "prost-build"
version = "0.1.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-build"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."

[dependencies]
bytes = "0.4"
curl = "0.4"
prost-codegen = { path = "../prost-codegen" }
prost = { path = ".." }
tempdir = "0.3"
zip = "0.2"
