[package]
name = "protoc-gen-rust"
version = "0.1.0"
authors = ["Dan Burkert <danburkert@apache.org>"]

[dependencies]
env_logger = "0.4"
itertools = "0.5"
log = "0.3"
proto = { path = ".." }
proto-derive = { path = "../proto-derive" }
