[package]
name = "proto-plugin"
version = "0.1.0"
authors = ["Dan Burkert <danburkert@apache.org>"]

[dependencies]
bytes = "0.4"
env_logger = "0.4"
itertools = "0.6"
log = "0.3"
multimap = "0.3"
proto = { path = ".." }
proto-derive = { path = "../proto-derive" }
