[package]
name = "prost-derive"
version = "0.1.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-derive"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."

[lib]
proc_macro = true

[dependencies]
error-chain = "0.10"
itertools = "0.6"
quote = "0.3"
syn = "0.11"
