[package]
name = "prost-derive"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
workspace = ".."

[lib]
proc_macro = true

[dependencies]
error-chain = "0.10"
itertools = "0.6"
quote = "0.3"
syn = { version = "0.11", features = ["aster", "visit"] }
